drop table AnObject if exists;
drop table ASubObject if exists;
create table AnObject (
    id bigint generated by default as identity,
    anObject bigint,
    myASubObject bigint,
    testInt integer,
    testString varchar(20),
    testLong bigint,
    testDate date,
    testBoolean boolean,
    testFloat float,
    testDouble double,
    primary key (id)
);
create table ASubObject (
    id bigint generated by default as identity,
    myASubObject bigint,
    name varchar(80),
    testString varchar(20),
    primary key (id)
);
alter table AnObject
    add constraint FKcc277t88h3i853t07k4l81lij
    foreign key (anObject)
    references AnObject;
alter table AnObject
    add constraint FKekncch2o599gwc9t148ygh9c6
    foreign key (myASubObject)
    references ASubObject;
alter table ASubObject
    add constraint FKowivfpy0agy32ba81eayhtgf
    foreign key (myASubObject)
    references ASubObject;
SELECT * FROM INFORMATION_SCHEMA.TABLES;
insert
into
    ASubObject
    (testString)
values
    ('testString');
insert
into
    AnObject
    ( testString, testLong, testDate, testBoolean, testFloat, testDouble)
values
    ( 'testString', 2, null, 0, 1.1, 2.2);
insert
into
    ASubObject
    (id, myASubObject, name, testString)
values
    (null, null, 'name', 'testString');
insert
into
    AnObject
    (id, anObject, myASubObject, testInt, testString, testLong, testDate, testBoolean, testFloat, testDouble)
values
    (null, null, null, 1, 'testString', 2, null, 0, 1.1, 2.2);