@startuml

title __CALLS's Class Diagram__\n

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.calls {
        class TemplateCallBEANTest {
            + executeBEANCreateTplNoFields()
            + executeBEANCreateTpl()
            + executeBeanInstanceVarsTpl()
            + executeBeanSetterTpl()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.calls {
        class TemplateCallCACHETest {
            + executeCACHECreateTpl()
            + executeAllKeysTpl()
            + executeBeanInstanceVarsTpl()
            + executeCacheSetterTpl()
            + executeCacheGetterTpl()
            + executeConfigBuilderSetterTpl()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.calls {
        class TemplateCallContantsTest {
            + executeConstantsCreateTpl()
            + executeConstantsLoopTpl()
            + executeEO()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.calls {
        class TemplateCallLoadModelTest {
            + executeJavaControl1Tpl()
            + executeJavaControl2Tpl()
            + executeJavaControl3Tpl()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.calls {
        class TemplateCallModuleTest {
            + staticValuesLoopTpl()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.calls {
        class TemplateCallPersistTest {
            + callTestModelsControlWithSaveTpl()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.calls {
        class TemplateCallStaticValuesTest {
            + staticValuesLoopTpl()
            + EOStaticJavaTemplate()
            + EOStaticJavaBySteps()
            + EOStaticJavaByStepsSimplified()
            + EOStaticJavaByStepsTest()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.calls {
        class TemplateCallTest {
            + callTestModelsControlTpl()
            + callModels()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
