@startuml

title __ELASTICOBJECTS's Class Diagram__\n

  package org.fluentcodes.projects.elasticobjects {
    class EO_STATIC {
        {static} + MODULE_SHORT : String
        {static} + ELASTIC_OBJECTS : String
        {static} + MODULE_NAME : String
        {static} + _PARENT_KEY : String
        {static} + _VALUE : String
        {static} + S_VALUE : String
        {static} + DYNAMIC_PATTERN : String
        {static} + MAIN : String
        {static} + BUILD : String
        {static} + TEST : String
        {static} + CP_CALLS : String
        {static} + CP_STATICS : String
        {static} + CP_CONFIG : String
        {static} + STRING : String
        {static} + MODULE : String
        {static} + A_CONFIG_PLACEHOLDER : String
        {static} + GENERIC_CONFIG : String
        {static} + FILE : String
        {static} + MODEL : String
        {static} + FIELD : String
        {static} + USER : String
        {static} + ROLE : String
        {static} + CONFIG : String
        {static} + CALL : String
        {static} + TEMPLATE : String
        {static} + VALUE : String
        {static} + JSON : String
        {static} + A_VALUES_SET : String
        {static} + A_VALUES_MAP : String
        {static} + A_VALUES : String
        {static} + A_VALUES_MAP_EXE : String
        {static} + A_VALUES_SET_EXE : String
        {static} + A_VALUES_TEMPLATE_EXE : String
        {static} + A_TEMPLATE_KEY : String
        {static} + HOST : String
        {static} + A_IF : String
        {static} + A_IF_LOOP : String
        {static} + A_KEEP : String
        {static} + A_EXECUTE : String
        {static} + A_PREFIX : String
        {static} + POSTFIX : String
        {static} + A_CONFIG : String
        {static} + CONFIG_JSON_END : String
        {static} + CONFIG_PATH_MAIN_SIMPLE : String
        {static} + CONFIG_PATH_TEST_SIMPLE : String
        {static} + CONFIG_PATH_MAIN : String
        {static} + CONFIG_PATH_TEST : String
        {static} + JSON_PATH_MAIN : String
        {static} + JSON_PATH_TEST : String
        {static} + CONFIG_MODEL : String
        {static} + CONFIG_MODEL_FILE : String
        {static} + CONFIG_MODEL_MAIN : String
        {static} + CONFIG_FIELD : String
        {static} + CONFIG_FIELD_FILE : String
        {static} + CONFIG_FIELD_MAIN : String
        {static} + CONFIG_HOST : String
        {static} + CONFIG_HOST_FILE : String
        {static} + CONFIG_HOST_MAIN : String
        {static} + CONFIG_HOST_TEST : String
        {static} + CONFIG_JSON : String
        {static} + CONFIG_JSON_FILE : String
        {static} + CONFIG_JSON_MAIN : String
        {static} + CONFIG_JSON_TEST : String
        {static} + CONFIG_CONFIG : String
        {static} + CONFIG_CONFIG_FILE : String
        {static} + CONFIG_CONFIG_MAIN : String
        {static} + CONFIG_CONFIG_TEST : String
        {static} + CONFIG_FILE : String
        {static} + CONFIG_FILE_FILE : String
        {static} + CONFIG_FILE_MAIN : String
        {static} + CONFIG_FILE_TEST : String
        {static} + CONFIG_TEMPLATE : String
        {static} + CONFIG_TEMPLATE_FILE : String
        {static} + CONFIG_TEMPLATE_MAIN : String
        {static} + CONFIG_TEMPLATE_TEST : String
        {static} + CONFIG_VALUE : String
        {static} + CONFIG_VALUE_FILE : String
        {static} + CONFIG_VALUE_TEST : String
        {static} + CONFIG_MODEL_PREFIX : String
        {static} + CONFIG_FIELD_PREFIX : String
        {static} + CONFIG_TEMPLATE_PREFIX : String
        {static} + F_INSERT : String
        {static} + F_INDENT : String
        {static} + F_CONFIG_CLASS : String
        {static} + F_CONTENT : String
        {static} + F_SERIALIZATION_TYPE : String
        {static} + F_TO_SERIALIZE : String
        {static} + F_PROVIDE_IN_ACTION : String
        {static} + F_DEFAULT_VALUE : String
        {static} + M_VALUE_CALL : String
        {static} + M_LINKED_HASH_SET : String
        {static} + M_DBFIELD_PARAMS : String
        {static} + M_VIEW_PARAMS : String
        {static} + M_EXECUTOR_ACTION : String
        {static} + M_OR : String
        {static} + M_VIEW_FIELD_PARAMS : String
        {static} + M_HASH_MAP : String
        {static} + M_FIELD_CONFIG : String
        {static} + M_ARRAY_LIST : String
        {static} + M_STRING : String
        {static} + M_LIST_PARAMS : String
        {static} + M_LINKED_HASH_MAP : String
        {static} + M_LIKE : String
        {static} + M_VALUE_CONFIG : String
        {static} + M_LIST : String
        {static} + M_MODELS_LIST : String
        {static} + M_BOOLEAN : String
        {static} + M_EOPARAMS : String
        {static} + M_SHORT : String
        {static} + M_DBPARAMS : String
        {static} + M_HASH_SET : String
        {static} + M_VALUES_CONTENT : String
        {static} + M_SHAPE_TYPES : String
        {static} + M_EXECUTOR_IMPL : String
        {static} + M_EXECUTOR_LIST : String
        {static} + M_MODEL_CONFIG_SET : String
        {static} + M_ASSET_CONFIG : String
        {static} + M_USER_CONFIG : String
        {static} + M_ASSET_ACTION : String
        {static} + M_DOUBLE : String
        {static} + M_MODEL_CONFIG_LIST : String
        {static} + M_MODEL_CONFIG_MAP : String
        {static} + M_FLOAT : String
        {static} + M_CONFIG_ACTION : String
        {static} + M_EXECUTOR_VALUES : String
        {static} + M_AND : String
        {static} + M_MODEL_INTERFACE : String
        {static} + M_LONG : String
        {static} + M_CLASS : String
        {static} + M_OBJECT : String
        {static} + M_ARRAYS : String
        {static} + M_MAP : String
        {static} + M_VALUE_ACTION : String
        {static} + M_EXECUTOR_LIST_TEMPLATE : String
        {static} + M_ACTION : String
        {static} + M_JSON_ACTION : String
        {static} + M_ROLE_PERMISSIONS : String
        {static} + M_SET : String
        {static} + M_STRING_BUILDER : String
        {static} + M_CONFIG : String
        {static} + M_JSON_CONFIG : String
        {static} + M_MODEL_CONFIG_NONE : String
        {static} + M_EQ : String
        {static} + M_VALUES_MATH : String
        {static} + M_MODEL_CONFIG : String
        {static} + M_PATH_PATTERN : String
        {static} + M_EXECUTOR : String
        {static} + M_ROLE_CONFIG : String
        {static} + M_LIST_MAPPER : String
        {static} + M_VALUES_CONTENT_HTML : String
        {static} + M_CONFIG_CONFIG : String
        {static} + M_HOST_CONFIG : String
        {static} + M_MODEL_IMPL : String
        {static} + M_LIST_CONFIG : String
        {static} + M_EOFIELD_PARAMS : String
        {static} + M_PASSWORD : String
        {static} + M_CONDITION : String
        {static} + M_PATH : String
        {static} + M_FILE_CONFIG : String
        {static} + M_LOGGING_OBJECTS_IMPL : String
        {static} + M_TEMPLATE_CONFIG : String
        {static} + M_VALUES_MISC : String
        {static} + M_VALUE_PARAMS_HELPER : String
        {static} + M_DATE : String
        {static} + M_INTEGER : String
        {static} + M_STRING_BUFFER : String
        {static} + M_SCOPE : String
        {static} + M_TEMPLATE_ACTION : String
        {static} + M_MODEL : String
        {static} + M_LIST_ACTION : String
        {static} + M_MODEL_CONFIG_SCALAR : String
        {static} + M_EOBUILDER : String
        {static} + M_MODEL_CONFIG_OBJECT : String
        {static} + M_HOST_ACTION : String
        {static} + M_FILE_ACTION : String
        {static} + M_CONFIG_IMPL : String
        {static} + F_DO_MAP : String
        {static} + F_UPPER_ID_KEY : String
        {static} + F_PATH_PATTERN_AS_STRING : String
        {static} + F_FILE_NAME : String
        {static} + F_NATURAL_ID : String
        {static} + F_LIST_MAPPER : String
        {static} + F_PATH : String
        {static} + F_PASSWORD : String
        {static} + F_PACKAGE_GROUP : String
        {static} + F_DB_FIELD_PARAMS : String
        {static} + F_ROLE_PERMISSIONS : String
        {static} + F_ACTION : String
        {static} + F_MODEL : String
        {static} + F_ID : String
        {static} + F_SHORT : String
        {static} + F_JOIN : String
        {static} + F_COL_KEYS : String
        {static} + F_WRITE : String
        {static} + F_AND_AS_STRING : String
        {static} + F_MODELS : String
        {static} + F_HIBERNATE_ANNOTATIONS : String
        {static} + F_NOT_NULL : String
        {static} + F_MODULE : String
        {static} + F_EXECUTE : String
        {static} + F_IGNORE_HEADER : String
        {static} + F_FILTER_SUB_MODULE : String
        {static} + F_SHAPE_TYPE : String
        {static} + F_UNIQUE : String
        {static} + F_INPUT_KEY : String
        {static} + F_VIEW_FIELD_PARAMS : String
        {static} + F_WHERE_AS_STRING : String
        {static} + F_TEMPLATE : String
        {static} + F_HOST_NAME : String
        {static} + F_LOG : String
        {static} + F_ROW_HEAD : String
        {static} + F_METHODS : String
        {static} + F_EO_FIELD_PARAMS : String
        {static} + F_EOPARAMS_CREATE : String
        {static} + F_FILE_KEY : String
        {static} + F_HIBERNATE : String
        {static} + F_COL_KEYS_AS_STRING : String
        {static} + F_LIST_PARAMS : String
        {static} + F_PERMISSIONS_CREATE : String
        {static} + F_CACHED : String
        {static} + F_ROW_START : String
        {static} + F_VIEW_PARAMS : String
        {static} + F_KEY : String
        {static} + F_SCS_KEY : String
        {static} + F_TABLE : String
        {static} + F_UPPER_ID : String
        {static} + F_LOOP_PATH : String
        {static} + F_VIEW_KEY : String
        {static} + F_EO_PARAMS : String
        {static} + F_CUSTOM_FIELD_PARAMS : String
        {static} + F_FIELD_KEYS : String
        {static} + F_MODEL_KEY : String
        {static} + F_FILTER : String
        {static} + F_ATTRIBUTES : String
        {static} + F_ROW_END : String
        {static} + F_CALC : String
        {static} + F_MAP_PATH : String
        {static} + F_DB_PARAMS : String
        {static} + F_PROTOCOL : String
        {static} + F_ACTION_MAP : String
        {static} + F_CREATE : String
        {static} + F_NATURAL_KEYS : String
        {static} + F_MODEL_KEYS : String
        {static} + F_INFO : String
        {static} + F_PACKAGE_PATH : String
        {static} + F_ROW_DELIMITER : String
        {static} + F_READ : String
        {static} + F_DEFAULT_IMPLEMENTATION : String
        {static} + F_FILTER_MODULE : String
        {static} + F_CUSTOM_PARAMS : String
        {static} + F_FIELD_KEY : String
        {static} + F_AUTHOR : String
        {static} + F_SUPER_KEY : String
        {static} + F_MODELS_LIST : String
        {static} + F_CREATION_DATE : String
        {static} + F_USER_KEY : String
        {static} + F_FILTER_KEY : String
        {static} + F_CONFIG_KEY : String
        {static} + F_ENTRIES : String
        {static} + F_ID_KEY : String
        {static} + F_PORT : String
        {static} + F_JSON_KEY : String
        {static} + F_SUB_MODULE : String
        {static} + F_NAME : String
        {static} + F_FIELDS : String
        {static} + F_JOIN_INVERSE : String
        {static} + F_OR_AS_STRING : String
        {static} + F_FIELD_NAME : String
        {static} + F_ATTRIBUTE_LIST : String
        {static} + F_ORIGIN : String
        {static} + F_ROLES : String
        {static} + F_DESCRIPTION : String
        {static} + F_FIELD_DELIMITER : String
        {static} + F_MODEL_CONFIG_KEY : String
        {static} + F_DELETE : String
        {static} + F_EXPANDED : String
        {static} + F_AND : String
        {static} + F_SCOPE : String
        {static} + F_PATH_PATTERN : String
        {static} + F_VALUE_KEY : String
        {static} + F_VALUE : String
        {static} + F_SERIALIZED : String
        {static} + F_INTERFACES : String
        {static} + F_OR : String
        {static} + F_FILE_PATH : String
        {static} + F_VALUE_AS_STRING : String
        {static} + F_LENGTH : String
        {static} + F_MAP_KEY : String
        {static} + F_HOST_KEY : String
        {static} + F_USER_NAME : String
        {static} + F_FILTER_CONFIG_CLASS : String
        {static} + F_FILTER_CONFIG_NAME : String
        {static} + F_USER : String
        {static} + F_TEMPLATE_KEY : String
        {static} + H_LOCALHOST : String
        {static} + H_LOCAL : String
        {static} + FILE_EO_STATIC_JAVA : String
        {static} + FILE_EO_STATIC_TEST_JAVA : String
        {static} + FILE_EO_STATIC_BUILD_JAVA : String
        {static} + J_CONTENT : String
        {static} + J_MODULE_CONFIG_JSON : String
        {static} + T_CONTENT : String
        {static} + CON_NEWLINE : String
        {static} + CON_TAB : String
        {static} + CON_SEMICOLON : String
        {static} + CON_SPACE : String
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
