<call values="map">
{"page1":{
    "1x":{
    "order":1,
        "page":"page1",
        "header":"header1",
        "summary":"summary1",
        "content":"content1",
        "additional":"additional1",
        "template":"HOptionsList",
        "headerLevel":1
    },
    "2x":{
    "order":2,
     "page":"page1",
            "header":"header1a",
            "summary":"summary1a",
            "content":"content1a",
            "additional":"additional1a",
            "template":"HOption",
            "headerLevel":1
    },
    "3x":{
    "order":3,
    "page":"page1",
        "header":"header2",
        "summary":"summary2",
        "content":"content2",
        "additional":"additional2",
        "template":"HOption",
        "headerLevel":2
    }
  }
}
</call>
<call templateKey="page.md" path="*"/>