@startuml

title __ELASTICOBJECTS's Class Diagram__\n

  package  {
    package org.fluentcodes.projects.elasticobjects {
      class H_EO_STATIC_TEST {
          {static} + H_H2_MEM_RIGHT_CONFIG : String
          {static} + H_H2_MEM_RIGHT : String
          {static} + H_H2_FILE_BASIC : String
          {static} + H_H2_MEM_BASIC : String
          {static} + H_H2_MEM_RIGHT_MAP : String
          {static} + H_H2_MEM_RIGHT_LIST : String
          {static} + H_H2_FILECREATE : String
          {static} + DB_H2_MEM_RIGHT : String
          {static} + DB_H2_MEM_RIGHT_MAP : String
          {static} + DB_H2_MEM_RIGHT_LIST : String
          {static} + HQ_H2_FILE_BASIC_TEST : String
          {static} + HQ_H2_FILE_SUB_TEST : String
          {static} + HQ_H2_MEM_BASIC_TEST : String
          {static} + HQ_H2_MEM_SUB_TEST : String
          {static} + HS_H2_BASIC_TEST_DROP : String
          {static} + HS_H2_BASIC_CREATE : String
          {static} + M_LEFT_LIST : String
          {static} + M_LEFT_MAP : String
          {static} + M_LEFT : String
          {static} + M_RIGHT_LIST : String
          {static} + M_RIGHT_MAP : String
          {static} + M_RIGHT : String
          {static} + F_COUNTRY : String
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      class TestDbProvider {
          {static} + findDbCache()
          {static} + findDbSqlCache()
          {static} + createAdapterWithActionBuilder()
          {static} + executeAdapterWithActionBuilderFromJSON()
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      class TestHProvider {
          {static} + findHibernateCache()
          {static} + findHibernateSqlCache()
          {static} + findHibernateModelCache()
          {static} + createHQueryAction()
          {static} + createHibernateModelActionRead()
          {static} + createHibernateModelActionRead()
          {static} + createHibernateModelActionWrite()
          {static} + createHibernateModelActionWrite()
          {static} + createHibernateModelActionDelete()
          {static} + createHibernateModelActionDelete()
          {static} + createAdapterWithActionBuilder()
          {static} + executeAdapterWithActionBuilderFromJSON()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
