@startuml

title __EO's Class Diagram__\n

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOCompareTest {
          {static} - LOG : Logger
          + simpleEquals()
          + simpleScalarNotEquals()
          + simpleContainerNotEquals()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOElementaryTest {
          {static} - LOG : Logger
          + isContainer()
          + getChild()
          + errorNonExistingPath()
          + errorGettingNotExistingObjectPath()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOGetTest {
          {static} - LOG : Logger
          + callNotExistingPaths_hasEmptyLog()
          + callNotExistingPathsAtTheEnd()
          + callNotExistingPathsWithin()
          + checkParentKey()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOJSONSerializationTypeTest {
          + setString()
          + setDoubleValue()
          + setLong()
          + setFloatValue()
          + setInt()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOKeysTest {
          {static} - LOG : Logger
          + keyPath()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOLogTest {
          {static} - LOG : Logger
          - createWarnAdapter()
          + errorWithException_WarnAdapter()
          + error_WarnAdapter()
          + warnWithException_WarnAdapter()
          + warn_WarnAdapter()
          + info_WarnAdapter()
          + debug_WarnAdapter()
          + info_InfoChildAdapter()
          + info_childAdapterHas_HasDefaultWarningFromParent()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathChildMap_models_Test {
          {static} - LOG : Logger
          + givenString_withInteger_changeNothing()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathChildMap_value_Test {
          {static} - LOG : Logger
          + givenMapString_withInteger_ok()
          + givenMapString_withMap_fails()
          + givenBTString_withMap_fails()
          + givenBTString_withInteger_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathChildMap_value_models_Test {
          {static} - LOG : Logger
          + givenMapString_withInteger_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathChildSet_models_Test {
          {static} - LOG : Logger
          - setEO_ok()
          - setEO_fails()
          + givenStringWithInteger()
          + givenStringWithMap()
          + givenBTWithBT()
          + givenBTWithMap()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathChildSet_value_Test {
          {static} - LOG : Logger
          + givenMapString_withInteger_ok()
          + givenMapString_withMap_ok()
          + givenListEmpty_withBoolean_ok()
          + givenBTMap_withMapString_ok()
          + givenBTString_withInteger_fails()
          + givenBTString_withBTInteger_fails()
          + givenBTString_withMapInteger_fails()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathChildSet_value_models_Test {
          {static} - LOG : Logger
          + givenMapString_withInteger_ok()
          + givenMapString_withMap_ok()
          + givenBTMap_withMapString_ok()
          + givenBTString_withInteger_fails()
          + givenBTString_withBTInteger_fails()
          + givenBTString_withMapInteger_fails()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathNewRootMap_models_Test {
          {static} - LOG : Logger
          + mapString_ok()
          + mapInteger_ok()
          + mapList_ok()
          + mapArrayList_ok()
          + mapListString_ok()
          + mapListBT_ok()
          + withJsnMapSmallList_ok()
          + mapMap_ok()
          + mapMapString_ok()
          + mapMapList_ok()
          + mapMapBT_ok()
          + mapHashMap_ok()
          + mapBT_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathNewRootMap_value_Test {
          {static} - LOG : Logger
          + mapNull_ok()
          + mapInteger_ok()
          + mapArrayList_ok()
          + mapHashMap_ok()
          + jsnMapEmpty_ok()
          + jsonMapEmpty2_ok()
          + jsonMapEmptyValues_ok()
          + jsonMapSmall_ok()
          + jsnMapSmall_ok()
          + jsonMapEmpty_ok()
          + jsnListEmpty_ok()
          + jsonListEmpty_ok()
          + mapBT_ok()
          + mapBTString_ok()
          + jsnBTEmpty_ok()
          + jsnBTSmall_ok()
          + jsonBTSmall_ok()
          + mapMap_ChangesInOriginalMap_HasNoChangeInEO()
          + mapMapWithSubMap_ok()
          + mapMapWithSubMap_fails()
          + setMapIntegerKey()
          + withList()
          + withBT_mapMapEmpty()
          + withJsnSTSimple()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathNewRootMap_value_models_Test {
          {static} - LOG : Logger
          + mapInteger_ok()
          + mapInteger_withString_ok()
          + mapArrayList_ok()
          + mapList_ok()
          + mapMap_ok()
          + mapHashMap_ok()
          + jsonMapEmptyList_ok()
          + jsonMapEmptyBT_ok()
          + jsonMapSmallBT_ok()
          + jsonListSmallBT_fails()
          + mapHashMapWithBT_ok()
          + mapBT_ok()
          + withST_ok()
          + withSTAndMap_ok()
          + mapBTStringWithMap_ok()
          + jsnMapEmptyST_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathNewRootSet_value_Test {
          {static} - LOG : Logger
          + withNull_ok()
          + withString_ok()
          + withInteger_ok()
          + withHashMap_ok()
          + withMapInteger_ok()
          + withArrayList_ok()
          + withBT_ok()
          + withBTTestString_ok()
          + withST_ok()
          + mapWithIntegerKey()
          + mapMap_ChangesInOriginalMap_changeInEO()
          + withList()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathNewRootSet_value_models_Test {
          {static} - LOG : Logger
          + withMapAndInteger_ok()
          + withBTAndInteger_ok()
          + withIntegerAndInteger_ok()
          + withIntegerAndHashMap_ok()
          + withListAndArrayList_ok()
          + withMapAndArrayList_ok()
          + withMapAndHashMap_ok()
          + withBTAndBT_ok()
          + withBTAndMap_ok()
          + withST_ok()
          + withSTAndMap_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathRootMap_models_Test {
          {static} - LOG : Logger
          {static} + mapEO_ok()
          {static} + mapEO_changeNothing()
          + givenString_withInteger_changeNothing()
          + givenString_WithList_changeNothing()
          + givenMapString_withMap_changeNothing()
          + givenMapWithString_withString_changeNothing()
          + givenBTWithString_withMap_changeNothing()
          + givenBTString_withMap_changeNothing()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathRootMap_value_Test {
          {static} - LOG : Logger
          + givenString_withInteger_ok()
          + givenString_withBoolean_ok()
          + givenString_withString_ok()
          + givenString_withMap_fails()
          + givenString_withBT_fails()
          + givenMapEmpty_withString_fails()
          + givenMapString_withEmptyMap_ok_changesNothing()
          + givenMapString_withLinkedHashMapEmpty_ok()
          + givenMapString_withMapInteger_ok()
          + givenMapEmpty_withST_ok()
          + givenMapEmpty_withJsonMap_ok()
          + givenMapString_withJsonMap_ok()
          + givenMapString_withJsonMapString_ok()
          + givenMapEmpty_withJsonMapBoolean_ok()
          + givenListEmpty_withBoolean_fails()
          + givenListEmpty_withBTBoolean_ok()
          + givenListStringEmpty_withBTBoolean_ok()
          + givenListStringEmpty_withSTString_ok()
          + givenMapEmpty_withJsonString_ok()
          + givenMapEmpty_withJsonBoolean_ok()
          + givenMapEmpty_withListJsonSmall_ok()
          + givenMapEmpty_withJsnListSmall_ok()
          + givenMapSmall_withJsonListSmall_ok()
          + givenMapSmall_withJsnListSmall2_fails()
          + givenListEmpty_withJsnEmpty_ok()
          + givenListEmpty_withJsnMapSmall_ok()
          + givenBTString_withMapInteger_ok()
          + givenBTWithString_withBTWithInteger_ok()
          + givenBTWithString_withMapWithInteger_ok()
          + givenBTWithString_withString_fails()
          + givenBTString_withMap_ok()
          + givenBTString_WithBTInteger_ok()
          + givenBTEmpty_withJSONMap_ok()
          + givenBTString_withJSONMap_ok()
          + givenListString_WithBTString_ok()
          + givenBTSmall_withJsonListSmall_fails()
          + givenBTEmpty_withJsnMapEmpty_ok()
          + givenBTEmpty_withJsnMapSmall_ok()
          + givenBTEmpty_withJsonMapWrongName_fails()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathRootMap_value_models_Test {
          {static} - LOG : Logger
          {static} + mapEO_ok()
          {static} + mapEO_fails()
          + givenString_withIntegerAndInteger_ok()
          + givenString_withBooleanAndInteger_ok()
          + givenString_WithMapAndList_fails()
          + givenMapString_withStringAndMap_fails()
          + givenMapWithString_withEmptyMapAndString_ok()
          + givenBTWithString_withBTWithInteger_ok()
          + givenBTWithString_withMapWithIntegerAndInteger_ok()
          + givenBTWithString_withString_fails()
          + givenBTString_withMap_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathRootSet_models_Test {
          {static} - LOG : Logger
          + givenString_withInteger_changeNothing()
          + givenMapString_WithInteger_changeNothing()
          + givenMapString_withHashMap_changeNothing()
          + givenBTString_withMap_changeNothing()
          + givenBTString_withInteger_changeNothing()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathRootSet_value_Test {
          {static} - LOG : Logger
          + givenString_withInteger_ok()
          + givenString_withBoolean_ok()
          + givenString_withMap_ok()
          + givenMapEmpy_withNull_ok()
          + givenMapEmpty_withString_ok()
          + givenMapString_withString_ok()
          + givenMapString_withMapEmpty_ok()
          + givenMapEmpty_withMapString_ok()
          + givenMapEmpty_withBT_ok()
          + givenMapEmpty_withSTString_ok()
          + givenListEmpty_withMapJsonSmall_ok()
          + givenBTString_withBTInteger_ok()
          + givenBTString_withMapInteger_ok()
          + givenBTString_withString_ok()
          + givenBTString_WithBTInteger_ok()
          + givenSTSimple_withSTString_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EONoPathRootSet_value_models_Test {
          {static} - LOG : Logger
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathMap_models_Test {
          {static} - LOG : Logger
          + givenMapString_withLinkedHashMapAtStringField_fails()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathMap_value_Test {
          {static} - LOG : Logger
          + givenString_withString_fails()
          + givenMapString_withString_ok()
          + givenMapEmpty_withString_ok()
          + givenMapString_withInteger_ok()
          + givenMapMapEmpty_withMapString_ok()
          + givenMapString_withLinkedHashMap_fails()
          + givenMapSTEmpty_withST_ok()
          + givenMapEmpty_withJsonMap_ok()
          + givenMapEmpty_withSTAndLongerPath()
          + givenMapEmpty_withMapPathAlreadyUsedByScalarTypeValue()
          + givenMapEmpty_withJsnSmallLevel0_ok()
          + givenMapEmpty_withJsonSmallLevel0_ok()
          + givenMapEmpty_withJsnSmallPath2_ok()
          + givenMapEmpty_withJsonSmallPath2_ok()
          + givenMapEmpty_withJsnAllPath2_ok()
          + givenMapEmpty_withJsonAllPath2_ok()
          + givenListEmpty_withBoolean_ok()
          + givenBTString_WithString_ok()
          + givenBTString_WithIntegerAtStringField_ok()
          + givenBTEmpty_WithIntegerAtStringField_ok()
          + givenBTEmpty_WithInteger_ok()
          + givenBTString_WithMap_fails()
          + givenBTEmpty_withUnknownFieldKey_fails()
          + givenBTDateEmpty_WithDate_ok()
          + givenBTUntypedMap_WithHashMap_ok()
          + givenBTST_withSTString_ok()
          + givenBTST_withMapString_ok()
          + givenBTST_withBTString_ok()
          + givenBTST_withJSONString_ok()
          + givenBTST_withJSONUnknown_fails()
          + givenBTMapST_withBTString_fails()
          + givenBTMapST_withJSONMap_fails()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathMap_value_models_Test {
          {static} - LOG : Logger
          + givenMapSTEmpty_withST_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathNewRootMap_models_Test {
          {static} - LOG : Logger
          + mapInteger_ok()
          + mapMap_ok()
          + mapHasMap_ok()
          + mapList_ok()
          + mapArrayList_ok()
          + mapBT_ok()
          + mapJsnEmptyBT_ok()
          + mapJsnSmallBT_ok()
          + mapJsnListSmallBT_fails()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathNewRootMap_value_Test {
          {static} - LOG : Logger
          + mapInteger_ok()
          + mapArrayList_ok()
          + mapList_ok()
          + mapMap_ok()
          + mapHashMap_ok()
          + withHashMapWithBT_ok()
          + withJsonSmallLevel0()
          + withJsonmallWithKeysAndList()
          + withListStringPath2()
          + mapBT_ok()
          + mapBTStringWithMap_ok()
          + jsnBTSmallLevel0_ok()
          + jsnBTSmallPath2_ok()
          + jsnBTAllPath2_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathNewRootMap_value_models_Test {
          {static} - LOG : Logger
          + mapInteger_ok()
          + mapArrayList_ok()
          + mapList_ok()
          + mapMap_ok()
          + mapHashMap_ok()
          + mapHashMapWithBT_ok()
          + mapBT_ok()
          + mapBTStringWithMap_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathNewRootSet_models_Test {
          {static} - LOG : Logger
          + setIntegerNull_ok()
          + setInteger_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathNewRootSet_value_Test {
          {static} - LOG : Logger
          + mapInteger_ok()
          + listWithPath2()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathSet_models_Test {
          {static} - LOG : Logger
          + givenMapString_withInteger_fails()
          + givenMapString_withMap_fails()
          + givenBTString_withMap_fails()
          + givenBTString_withInteger_fails()
          + givenBTUntypedMap_withHashMap_fails()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathSet_value_Test {
          {static} - LOG : Logger
          + givenMapString_withString_ok()
          + givenString_withStringToString_fails()
          + givenString_withIntegerToString_fails()
          + givenMapEmpty_withStringPath2_ok()
          + givenMapString_withHashMap_ok()
          + givenMapStringTyped_withInteger_ok()
          + givenMapStringTyped_withHashMap_fails()
          + givenMapMapString_withString_ok()
          + givenListEmpty_withBoolean_ok()
          + givenMapEmpty_withListStringLevel0()
          + givenBTString_withString_ok()
          + givenBTString_withInteger_fails()
          + givenBTIntegerEmpty_withInteger_ok()
          + givenBTLongEmpty_withLong_ok()
          + givenBTDoubleEmpty_withDouble_ok()
          + givenBTDatempty_withDate_ok()
          + givenBTUnknownEmpty_withString_fails()
          + givenBTFloatEmpty_withFloat_ok()
          + givenBTFloatEmpty_withString_ok()
          + givenBTObjectEmpty_withHashMap_fails()
          + givenBTString_withLinkedHashMap_fails()
          + givenBTUntypedMap_withLinkedHashMap_ok()
          + givenBTEmpty_withSTString_ok()
          + setWithLongSTPath_storeValueWithSTModel()
          + givenBTMapST_withString_fails()
          + givenListBTEmpty_withSTString_ok()
          + givenListBTEmpty_withSTStringAt1_ok()
          + givenListBTEmpty_withMap_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPathSet_value_models_Test {
          {static} - LOG : Logger
          + givenString_withStringAndString_ok()
          + givenMapString_withString_ok()
          + givenMapString_withStringAndHashMap_ok()
          + givenBTString_withStringAndMap_ok()
          + givenBTString_withIntegerAndInteger_ok()
          + givenBTUntypedMap_WithHashMapMap_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPath_Test {
          {static} - LOG : Logger
          + withPath2()
          + withPath4()
          + withPath3()
          + withPath3AndWithCommonPart()
          + withPath3WithCommon2Parts()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOPath_value_Test {
          {static} - LOG : Logger
          + givenMapStringLevel0_setMapStringLevel1_ok()
          + givenMapStringLevel1_setMapStringLevel0_ok()
          + givenMapStringLevel1_setMapStringLevel0WithOverWrite_ok()
          + givenMapStringLevel0_mapMapStringLevel1_ok()
          + givenMapStringLevel1_mapMapStringLevel0_ok()
          + givenMapStringLevel1_mapMapStringLevel0WithOverwrite_fails()
          + mapWithPathOverwrite_willWriteIntoTheLog()
          + mapWithPathsOverlapping()
          + mapWithPathLong()
          + setWithPath2()
          + setWithPath3()
          + setWithPath4()
          + setWithTwoPathsDistinct()
          + setWithPathWithCommonPart()
          + setWithPathWithCommon2Parts()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EORemoveTest {
          {static} - LOG : Logger
          - createBuilder()
          + object()
          + map()
          + list()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOToJSONBTTest {
          + mapDefault()
          + withIndent0()
          + withIndent1()
          + withIndent2()
          + withSTANDARD()
          + withEO()
          + withString()
          + withInteger()
          + withLong()
          + withFloat()
          + withFloatStandard()
          + withDouble()
          + withDate()
          + withBoolean()
          + withMap()
          + withList()
          + withBasicTest()
          + withSubTest()
          + withSubTestMap()
          + withSubTestList()
          + withSmall()
          + withSimple()
          + withAll()
          + withSubTestMapAndSerializationTypePARAMS()
          + withIndentAndSerializationTypeSCALAR_TYPES()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOToJSONConfigTest {
          + configImpl()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOToJSONListTest {
          + withDefault()
          + withIndent0()
          + withIndent1()
          + withIndent2()
          + withEmpty()
          + withString()
          + withStringJSON()
          + withStringScalarTypes()
          + withInteger()
          + withIntegerJSON()
          + withIntegerScalarTypes()
          + withLong()
          + withLongJSON()
          + withLongScalar()
          + compareEOFloat()
          + withFloatScalar()
          + withDouble()
          + withDoubleJSON()
          + withDoubleScalar()
          + withDate()
          + withDateJSON()
          + withDateScalar()
          + withBoolean()
          + withBooleanJSON()
          + withBooleanScalar()
          + withMap()
          + withMapJSON()
          + withList()
          + withListJSON()
          + withBasicTest()
          + withBasicTestJSON()
          + withSubTest()
          + withSubTestJSON()
          + withSmall()
          + withSmallJSON()
          + withSimple()
          + withSimpleJSON()
          + withIndentAndSerializationTypeSTANDARD()
          + withAll()
          + withAllJSON()
          + withIndentAndSerializationTypeSCALAR()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOToJSONMapTest {
          + withDefault()
          + withIndent0()
          + withIndent1()
          + withIndent2()
          + withStringScalar()
          + withIntegerScalar()
          + withLongScalar()
          + withFloatScalar()
          + withDoubleScalar()
          + withDateScalar()
          + withBooleanScalar()
          + withIndentScalar()
          + loopScalar()
          + mapBigAdapter10000()
          + mapBigAdapterUnexpanded10000()
          + setSameMaps()
          + setSameMapsWithCheck()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOToJSONSTTest {
          + mapDefault()
          + withIndent0()
          + withIndent1()
          + withIndent2()
          + withSTANDARD()
          + withString()
          + withName()
          + withSubTest()
          + withSimple()
          + withAll()
          + withIndentScalar()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class EOToJSONTest {
          + setSameMaps()
          + setSameMapsWithCheck()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class JSONToEOArrayTest {
          {static} - LOG : Logger
          + test()
          + testFromFile()
          + testDouble()
          + testSmall()
          + testAll()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class JSONToEOCallsTest {
          {static} - LOG : Logger
          {static} - SCS_CALL_SOURCE : String
          {static} - SCS_CALL_SOURCE_PATH : String
          {static} - SCS_CALL_SOURCE_JOINED : String
          + scsCallSource()
          + scsCallSourcePath()
          + scsCallSourceJoined()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class JSONToEOElementaryTest {
          {static} - LOG : Logger
          + test()
          + testNewLineAsPartOfAStringValue()
          + testArray()
          + testNewLineEscapedArray()
          + testNewLine2EscapedArray()
          + testCombinationsOfEscapes()
          + MapWithValueAndNoEndQuote_fails()
          + exceptionMap_Value_NoStartQuote()
          + exceptionMap_NoColon()
          + exceptionMap_Key_NoEndQuote()
          + exceptionMap_Key_NoStartQuote()
          + stringNotQuoted_setValue()
          + exceptionList_NoEndColon()
          + exceptionList_NoStartColon()
          + exceptionList_NoColon()
          + exceptionList_NoClosingBracket()
          + exceptionList_NoSeparatedValues()
          + ListWithFurtherValue_fails()
          + ListWrongStartValues_fails()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class JSONToEOMapTest {
          {static} - LOG : Logger
          + test()
          + testFromFile()
          + testDouble()
          + testSmall()
          + testAll()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelConfigTest {
          {static} - LOG : Logger
          - createBuilder()
          + withModelBasicTestMapNotEmpty()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsBTSTTest {
          {static} - LOG : Logger
          + setEmpty_ok()
          + mapEmpty_ok()
          + setJsonToEO_fails()
          + mapJsonToEO_okWithModelST_IsTypeOfTheField()
          + mapString_fails()
          + setString_fails()
          + setMap_fails()
          + mapMap_ok()
          + setList_fails()
          + mapList_fails()
          + setSubTest_ok()
          + setBasicTest_fails()
          + mapBasicTest_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsBTTest {
          {static} - LOG : Logger
          + withBT()
          + withBTString()
          + withMapBT()
          + withBT_createChildTestString()
          + withBT_createChildNotExisting_ThrowException()
          + withBT_createChildForScalarAndValueNonScalar_ThrowException()
          + withBT_createChildForNonScalarAndValueScalar_ThrowException()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsCheckRootValueTest {
          {static} - LOG : Logger
          + withString_withNullAndMap_keepString()
          + withString_withIntegerAndMap_keepString()
          + withMap_withIntegerAndMap_fails()
          + withMap_withIntegerAndSet_fails()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsEmptyTest {
          {static} - LOG : Logger
          + basic()
          + childString()
          + childNull()
          + childNullWithNameNull()
          + childArrayList()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsListMapTest {
          {static} - LOG : Logger
          {static} - SUB_CLASS : Class
          {static} - NAME : String
          {static} - MODELS : Models
          {static} - createModels()
          + setNull_ok()
          + mapNull_ok()
          + setJson_fails()
          + mapJson_ok()
          + mapString_fails()
          + setString_fails()
          + setMap_fails()
          + mapMap_ok()
          + setList_ok()
          + mapList_ok()
          + setBT_fails()
          + mapBT_ok()
          + mapST_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsMapBTTest {
          {static} - LOG : Logger
          {static} - SUB_CLASS : Class
          {static} - NAME : String
          {static} - MODELS : Models
          {static} - createModels()
          + setNull_ok()
          + mapNull_ok()
          + setJson_fails()
          + mapJson_ok()
          + mapString_fails()
          + setString_fails()
          + setMap_fails()
          + mapMap_ok()
          + setList_fails()
          + mapList_fails()
          + setST_fails()
          + mapST_ok()
          + mapBT_ok()
          + setBT_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsMapElementaryTest {
          {static} - LOG : Logger
          + withMap()
          + withMapList()
          + withMapObject()
          + withMapListMapList()
          + withMapStringValue()
          + childMapStringValueAndStringClass()
          + childMapStringValueAndEmptyClass()
          + childMapStringValueAndNullClass()
          + childMapStringValueAndMapClass()
          + childMapBTValueAndMapClass()
          + childMapBTValueAndBTClass()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsMapMapTest {
          {static} - LOG : Logger
          {static} - SUB_CLASS : Class
          {static} - NAME : String
          {static} - MODELS : Models
          {static} - createModels()
          + setNull_ok()
          + mapNull_ok()
          + setJson_fails()
          + mapJson_ok()
          + mapString_fails()
          + setString_fails()
          + setMap_fails()
          + mapMap_ok()
          + setList_fails()
          + mapList_ok()
          + setBT_fails()
          + mapBT_ok()
          + mapST_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsMapSTTest {
          {static} - LOG : Logger
          {static} - SUB_CLASS : Class
          {static} - NAME : String
          {static} - MODELS : Models
          {static} - createModels()
          + setNull_ok()
          + mapNull_ok()
          + setJson_fails()
          + mapJson_ok()
          + mapString_fails()
          + setString_fails()
          + setMap_fails()
          + mapMap_ok()
          + setList_fails()
          + mapList_fails()
          + setBT_fails()
          + mapBT_ok()
          + setST_ok()
          + mapST_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsMapStringTest {
          {static} - LOG : Logger
          {static} - SUB_CLASS : Class
          {static} - NAME : String
          {static} - MODELS : Models
          {static} - createModels()
          + setNull_ok()
          + mapNull_ok()
          + setJson_fails()
          + mapJson_fails()
          + mapString_ok()
          + setString_ok()
          + mapDate_ok()
          + setDate_ok()
          + setMap_fails()
          + mapMap_fails()
          + setList_fails()
          + mapList_fails()
          + setBT_fails()
          + mapBT_fails()
          + mapST_fails()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsMapTest {
          {static} - LOG : Logger
          {static} - MODELS : Models
          {static} - createModels()
          + setNull_ok()
          + mapNull_ok()
          + setJson_fails()
          + mapJson_ok()
          + mapString_ok()
          + setString_ok()
          + mapStringWithDateClass_ok()
          + setMap_ok()
          + mapMap_ok()
          + setList_ok()
          + mapList_ok()
          + setBT_ok()
          + mapBT_ok()
          + mapST_ok()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsScalarTest {
          {static} - LOG : Logger
          + withString()
          + withBTString()
          + withMapBT()
          + withBT_childTestString()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class ModelsTest {
          {static} - LOG : Logger
          + withModelInterface()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.eo {
      class NoPath {
          {static} - LOG : Logger
          + empty()
      }
    }
  }
  

  EOCompareTest -up-|> TestHelper
  EOElementaryTest -up-|> TestHelper
  EOGetTest -up-|> TestHelper
  EOJSONSerializationTypeTest -up-|> TestHelper
  EOKeysTest -up-|> TestHelper
  EOLogTest -up-|> TestHelper
  EONoPathChildMap_models_Test -up-|> TestHelper
  EONoPathChildMap_value_Test -up-|> TestHelper
  EONoPathChildMap_value_models_Test -up-|> TestHelper
  EONoPathChildSet_models_Test -up-|> TestHelper
  EONoPathChildSet_value_Test -up-|> TestHelper
  EONoPathChildSet_value_models_Test -up-|> TestHelper
  EONoPathNewRootMap_models_Test -up-|> TestHelper
  EONoPathNewRootMap_value_Test -up-|> TestHelper
  EONoPathNewRootSet_value_models_Test -up-|> TestHelper
  EONoPathRootSet_models_Test -up-|> TestHelper
  EOPathMap_models_Test -up-|> TestHelper
  EOPathMap_value_Test -up-|> TestHelper
  EOPathMap_value_models_Test -up-|> TestHelper
  EOPathNewRootMap_models_Test -up-|> TestHelper
  EOPathNewRootSet_models_Test -up-|> TestHelper
  EOPathSet_models_Test -up-|> TestHelper
  EOPathSet_value_Test -up-|> TestHelper
  EOPathSet_value_models_Test -up-|> TestHelper
  EOPath_Test -up-|> TestHelper
  EOPath_value_Test -up-|> TestHelper
  EORemoveTest -up-|> TestHelper
  EOToJSONBTTest -up-|> TestHelper
  EOToJSONConfigTest -up-|> TestHelper
  EOToJSONListTest -up-|> TestHelper
  EOToJSONMapTest -up-|> TestHelper
  EOToJSONSTTest -up-|> TestHelper
  EOToJSONTest -up-|> TestHelper
  JSONToEOArrayTest -up-|> TestHelper
  JSONToEOCallsTest -up-|> TestHelper
  JSONToEOElementaryTest -up-|> TestHelper
  JSONToEOMapTest -up-|> TestHelper
  ModelConfigTest -up-|> TestHelper
  ModelsBTSTTest -up-|> TestHelper
  ModelsBTTest -up-|> TestHelper
  ModelsCheckRootValueTest -up-|> TestHelper
  ModelsEmptyTest -up-|> TestHelper
  ModelsListMapTest -up-|> TestHelper
  ModelsMapBTTest -up-|> TestHelper
  ModelsMapElementaryTest -up-|> TestHelper
  ModelsMapMapTest -up-|> TestHelper
  ModelsMapSTTest -up-|> TestHelper
  ModelsMapStringTest -up-|> TestHelper
  ModelsMapTest -up-|> TestHelper
  ModelsScalarTest -up-|> TestHelper
  ModelsTest -up-|> TestHelper
  NoPath -up-|> TestHelper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
