@startuml

title __MODELS's Class Diagram__\n

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class Country {
            {static} - LOG : Logger
            - name : String
            - countryCode : String
            + getName()
            + setName()
            + getCountryCode()
            + setCountryCode()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class CountryTest {
            {static} - LOG : Logger
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class Left {
            {static} - LOG : Logger
            - id : Long
            - leftName : String
            - rightMap : Map<String, Right>
            - rightList : List<Right>
            + getId()
            + setId()
            + getLeftName()
            + setLeftName()
            + getRightMap()
            + setRightMap()
            + getRightList()
            + setRightList()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class LeftList {
            {static} - LOG : Logger
            - id : Long
            - leftName : String
            - rightList : List<RightList>
            + getId()
            + setId()
            + getLeftName()
            + setLeftName()
            + getRightList()
            + setRightList()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class LeftMap {
            {static} - LOG : Logger
            - id : Long
            - leftName : String
            - rightMap : Map<String, RightMap>
            + getId()
            + setId()
            + getLeftName()
            + setLeftName()
            + getRightMap()
            + setRightMap()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class LeftTest {
            {static} - LOG : Logger
            + checkLeft()
            + checkLeftListMany()
            + checkLeftMapMany()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class LocalizedEntry {
            {static} - LOG : Logger
            - countryCode : String
            - localizedString : LocalizedString
            + getCountryCode()
            + setCountryCode()
            + getLocalizedString()
            + setLocalizedString()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class LocalizedEntryTest {
            {static} - LOG : Logger
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class LocalizedString {
            {static} - LOG : Logger
            - localizedEntryMap : Map<String, LocalizedEntry>
            + getLocalizedEntryMap()
            + setLocalizedEntryMap()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class LocalizedStringTest {
            {static} - LOG : Logger
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class Right {
            {static} - LOG : Logger
            - id : Long
            - rightName : String
            - leftMap : Map<String, Left>
            - leftList : List<Left>
            + getId()
            + setId()
            + getRightName()
            + setRightName()
            + getLeftMap()
            + setLeftMap()
            + getLeftList()
            + setLeftList()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class RightList {
            {static} - LOG : Logger
            - id : Long
            - rightName : String
            - leftList : List<LeftList>
            + getId()
            + setId()
            + getRightName()
            + setRightName()
            + getLeftList()
            + setLeftList()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class RightMap {
            {static} - LOG : Logger
            - id : Long
            - rightName : String
            - leftMap : Map<String, LeftMap>
            + getId()
            + setId()
            + getRightName()
            + setRightName()
            + getLeftMap()
            + setLeftMap()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.models {
        class RightTest {
            {static} - LOG : Logger
            + checkRight()
            + checkRightListMany()
            + checkRightMapMany()
            + readRightMap()
            + readRightList()
            + readRight()
            + elementary()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
