@startuml

title __CONFIG's Class Diagram__\n

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ConfigConfigTest {
          {static} - LOG : Logger
          + readConfigConfigMain()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ConfigDivTest {
          {static} - LOG : Logger
          + testMap()
          + testString()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ConfigImplTest {
          {static} - LOG : Logger
          + assertModelCache()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ConfigsModelTest {
          + devFindClassBTQualified()
          + devFindClassBT()
          + checkModelCalls()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class DbParamsTest {
          + initDbParams()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class DivReflectionTest {
          {static} - METHOD_SET_TEST : String
          {static} - METHOD_SET_TEST_OBJECT : String
          + callObjectClass()
          + callObjectSetter()
          + callObjectSetterNull()
          + callBasicTestTestObject()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ObjectClass {
          - test : Object
          + getTest()
          + setTest()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class EOConfigsConfigTest {
          {static} - LOG : Logger
          + checkConfigsCache()
          + checkConfigsCacheWithST()
          + checkConfigsCacheDev()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class EoParamsTest {
          + initDbParams()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class FieldConfigTest {
          + findFieldConfigInModelCache()
          + readConfigClassPath()
          + readConfigMain()
          + readMapMain()
          + getId()
          + testBasicTestWithTestString()
          + assertId()
          + assertID()
          + assertTestObject()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class FileConfigTest {
          {static} - LOG : Logger
          + findConfigInCache()
          + readConfigClassPath()
          + readMapTest()
          + readConfigTest()
          + fromEoConfigsCache()
          + createWithTargetTxt()
          + createWithTestSourceTxt()
          + createWithSourceTxt()
          + createWithClasspathSourceTxt()
          + createWithLocalhostSourceTxt()
          + withFileKeyTest()
          + assertListFileCache()
          + createActionWithSourceTxt()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class HostConfigTest {
          {static} - LOG : Logger
          {static} - HOST_SCOPE : String
          {static} - HOST_PERMISSION : String
          + byAdapterPermissions()
          + readHostConfigMain()
          + byAdapterScope()
          + withHostKeyTest()
          + createWithBean()
          + getLocalHost()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class JsonConfigTest {
          {static} - LOG : Logger
          + findConfigInCache()
          + readConfigClassPath()
          + readMapTest()
          + readConfigTest()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ModelConfigDevTest {
          {static} - LOG : Logger
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ModelConfigListTest {
          + readMainJackson()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ModelConfigMapTest {
          + readMainJackson()
          + assertMap()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ModelConfigNoneTest {
          + assertObject()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ModelConfigObjectTest {
          {static} - LOG : Logger
          + createExecutorAction()
          + assertBTTypeTest()
          + assertBT()
          + getModel()
          + assertST()
          + getST()
          + assertBTFieldTest()
          + assertScsConfigTest()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ModelConfigScalarTest {
          + readMainJacksonString()
          + assertString()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ModelConfigTest {
          {static} - LOG : Logger
          {static} - MODEL_CONFIG_MAP : Map<String, Object>
          {static} - F_BUILD : String
          {static} - M_BUILDER : String
          + readModelConfigMain()
          + findCachedUnknown_fails()
          + findCachedString()
          + findCachedST()
          + modelTest()
          + assertLoggingObjectImpl()
          + assertAdapterBuilder()
          + checkDependentModels()
          + callStaticMethods()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ModelShapeTypesTest {
          {static} - LOG : Logger
          + testTypeClasses()
          + testTypeObjects()
          - testTypeClass()
          - testTypeObject()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class RolePermissionTest {
          {static} - LOG : Logger
          + testRoles()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ScsConfigTest {
          {static} - LOG : Logger
          + fromSourceCsv()
          + fromTargetCsv()
          + fromTest()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class TemplateConfigTest {
          {static} - LOG : Logger
          + findCache()
          + readCacheTest()
          + readMapTest()
          + readMapMain()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.config {
      class ValueConfigTest {
          {static} - LOG : Logger
          + testItemTestFromProvider()
          + findIntValue1()
          + findContent()
          + readValueConfigTest()
      }
    }
  }
  

  ConfigConfigTest -up-|> TestHelper
  ConfigDivTest -up-|> TestHelper
  ConfigImplTest -up-|> TestHelper
  DivReflectionTest +-down- ObjectClass
  EOConfigsConfigTest -up-|> TestHelper
  FieldConfigTest -up-|> TestHelper
  FileConfigTest -up-|> TestHelper
  HostConfigTest -up-|> TestHelper
  JsonConfigTest -up-|> TestHelper
  ModelConfigListTest -up-|> TestHelper
  ModelConfigMapTest -up-|> TestHelper
  ModelConfigNoneTest -up-|> TestHelper
  ModelConfigObjectTest -up-|> TestHelper
  ModelConfigScalarTest -up-|> TestHelper
  ModelConfigTest -up-|> TestHelper
  RolePermissionTest -up-|> TestHelper
  ScsConfigTest -up-|> TestHelper
  ValueConfigTest -up-|> TestHelper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
