@startuml

title __ELASTICOBJECTS's Class Diagram__\n

  package  {
    package org.fluentcodes.projects.elasticobjects {
      class B_STATIC {
          {static} + BUILDER : String
          {static} + MODULE_NAME : String
          {static} + TPL_JSON_CONTROL : String
          {static} + T_CONFIG_BUILDER_SETTER_TPL : String
          {static} + T_CONSTANTS_LOOP_TPL : String
          {static} + T_CONSTANTS_CREATE_TPL : String
          {static} + T_STATIC_EMPTY_TPL : String
          {static} + T_STATIC_VALUES_ENTRY_TPL : String
          {static} + T_STATIC_VALUES_EO_STATIC_TPL : String
          {static} + T_STATIC_VALUES_LOOP_TPL : String
          {static} + T_CACHE_CREATE_TPL : String
          {static} + T_BEAN_SETTER_TPL : String
          {static} + T_BEAN_CREATE_TPL : String
          {static} + T_BEAN_INSTANCE_VARS_TPL : String
          {static} + T_ALL_KEYS_TPL : String
          {static} + T_CACHE_INSTANCE_VARS_TPL : String
          {static} + T_CACHE_SETTER_TPL : String
          {static} + T_CACHE_GETTER_TPL : String
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      class Creator {
          {static} + EO_CONFIGS_CACHE : EOConfigsCache
          {static} - LOG : Logger
          {static} + main()
          {static} - checkParams()
          {static} - getModelKeysFromModule()
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      class CreatorJsonConfig {
          - configsCache : EOConfigsCache
          + CreatorJsonConfig()
          + createJson()
          + createJson()
          - getAsAttributes()
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      interface CreatorParams {
          {static} + MODELS_MAP_PATH : String
          {static} + FIELDS_MAP_PATH : String
          {abstract} + getExecute()
          {abstract} + getModule()
          {abstract} + getSubModule()
          {abstract} + getFilter()
          {abstract} + getActionKeys()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
