@startuml

title __EXECUTOR's Class Diagram__\n

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.executor {
        class ValueFieldsJava {
            {static} # getFieldDbParams()
            {static} # getFieldEoParams()
            {static} # getFieldDbParams()
            {static} # getFieldParams()
            {static} - getModelKeys()
            {static} - getModelShapeType()
            {static} + getModelKeys()
            {static} + getDefaultValue()
            {static} # getModelKeys()
            {static} + createInstanceVar()
            {static} + createType()
            {static} + createDescription()
            {static} # createAnnotation()
            {static} # fieldAllAttributes()
            {static} # addAttribute()
            {static} # hasTypeOrClass()
            {static} # getOneToManyAnnotation()
            {static} # getManyToOneAnnotation()
            {static} # getManyToManyAnnotation()
            {static} # getMapKeyAnnotation()
            {static} + getManyToManyInverseJoin()
            {static} + getManyToManyJoin()
            {static} # getJoinTable()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.executor {
        enum FIELD_KEY_MAP {
          column
          unique
          length
          notnull
          annotation
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.executor {
        class ValueModelsJava {
            {static} + getModelParams()
            {static} + getModelEoParams()
            {static} + getModelDbParams()
            {static} + getModelEoParams()
            {static} + getModelDbParams()
            {static} + createClassHeader()
            {static} + createImport()
            {static} + createInstanceVars()
            {static} - getPackagePath()
            {static} - getFields()
        }
      }
    }
  }
  

  package  {
    package org.fluentcodes.projects.elasticobjects {
      package org.fluentcodes.projects.elasticobjects.executor {
        enum MODEL_KEY_MAP {
          column
          idkey
          annotation
        }
      }
    }
  }
  

  ValueFieldsJava +-down- FIELD_KEY_MAP
  ValueModelsJava +-down- MODEL_KEY_MAP


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
