@startuml

title __PATHS's Class Diagram__\n

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.paths {
      class PathPatternFilterTest {
          {static} - TEST3 : String
          {static} + values : List<String>
          {static} - LOG : Logger
          + filterListTest()
          + filterWithEmptyStringConstructor()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.paths {
      class PathPatternTest {
          {static} - LOG : Logger
          + createPathPatternExample()
          + compareSerialized()
          + getPathListTest()
          + getFirstPathTest()
          + getFirstPathFilteredTest()
          + toStringTest()
      }
    }
  }
  

  package org.fluentcodes.projects.elasticobjects {
    package org.fluentcodes.projects.elasticobjects.paths {
      class PathTest {
          {static} - LOG : Logger
          + constructorStringEmpty()
          + constructorString_3Entries()
          + constructorString_BackAtTheBeginning()
          + constructorString_SeveralBacksAtTheBeginning()
          + constructorString_BackAtTheMiddle()
          + constructorString_BackAtTheEnd()
          + constructorPath()
          + childPath()
          + firstEntry()
          + hasMatcher()
          + hasPlaceHolder()
          + callToString()
      }
    }
  }
  

  PathPatternFilterTest -up-|> TestHelper
  PathPatternTest -up-|> TestHelper
  PathTest -up-|> TestHelper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
